### ISSUE TITLE
Drakov returns error when GET request has content-type: application/json in header

### ISSUE THREAD

**Issue by ahmad2x4** [Aconex/drakov#13]
Unit test fails when a GET request has header with content-type: application/json
e.g

### Retrieve all the things [GET]
+ Request 
    + Header

      content-type: application/json

unit test fails and return following error

  Error: expected [ { text: 'Zip2', id: '1' },
    { text: 'X.com', id: '2' },
    { text: 'SpaceX', id: '3' },
    { text: 'Solar City', id: '4' },
    { text: 'Hyperloop', id: '5' } ] response body, got {}
      at error (C:\Users\Ahmadreza\Documents\GitHub\drakov\node_modules\supertest\lib\test.js:235:13)
      at Test.assert (C:\Users\Ahmadreza\Documents\GitHub\drakov\node_modules\supertest\lib\test.js:166:19)
      at assert (C:\Users\Ahmadreza\Documents\GitHub\drakov\node_modules\supertest\lib\test.js:132:12)
      at C:\Users\Ahmadreza\Documents\GitHub\drakov\node_modules\supertest\lib\test.js:129:5
      at Test.Request.callback (C:\Users\Ahmadreza\Documents\GitHub\drakov\node_modules\supertest\node_modules\superagent\lib\node\index.js:746:30)
      at Test.<anonymous> (C:\Users\Ahmadreza\Documents\GitHub\drakov\node_modules\supertest\node_modules\superagent\lib\node\index.js:135:10)
      at Test.emit (events.js:95:17)
      at IncomingMessage.<anonymous> (C:\Users\Ahmadreza\Documents\GitHub\drakov\node_modules\supertest\node_modules\superagent\lib\node\index.js:938:12)
      at IncomingMessage.emit (events.js:117:20)
      at _stream_readable.js:943:16

**Comment by marcelogo** [comment]
Fixed in version 0.0.13
