### ISSUE TITLE
Line ending

### ISSUE THREAD

**Issue by gpminsuk** [Aconex/drakov#149]
Hi, I'm a Windows user and running Drakov with Windows line ending does not work.

Is it a bug?

[INFO] No configuration files found
[INFO] Loading configuration from CLI
   DRAKOV STARTED
{ Error: Error parsing blueprint!
    at Object.Module.parse (C:\Users\mika\AppData\Roaming\npm\node_modules\drakov\node_modules\drafter.js\lib\drafter.no
mem.js:20:7869)
    at C:\Users\mika\AppData\Roaming\npm\node_modules\drakov\lib\parse\blueprint.js:13:17
    at C:\Users\mika\AppData\Roaming\npm\node_modules\drakov\node_modules\async\lib\async.js:718:13
    at iterate (C:\Users\mika\AppData\Roaming\npm\node_modules\drakov\node_modules\async\lib\async.js:262:13)
    at async.forEachOfSeries.async.eachOfSeries (C:\Users\mika\AppData\Roaming\npm\node_modules\drakov\node_modules\asyn
c\lib\async.js:281:9)
    at _parallel (C:\Users\mika\AppData\Roaming\npm\node_modules\drakov\node_modules\async\lib\async.js:717:9)
    at Object.async.series (C:\Users\mika\AppData\Roaming\npm\node_modules\drakov\node_modules\async\lib\async.js:739:9)
    at C:\Users\mika\AppData\Roaming\npm\node_modules\drakov\lib\middleware\route-map.js:23:15
    at f (C:\Users\mika\AppData\Roaming\npm\node_modules\drakov\node_modules\once\once.js:25:25)
    at Glob.<anonymous> (C:\Users\mika\AppData\Roaming\npm\node_modules\drakov\node_modules\glob\glob.js:151:7)
  result:
   { _version: '2.2',
     error:
      { code: 2,
        message: 'the use of carriage return(s) \'\\r\' in source data isn\'t currently supported, please contact makers
',
        location: [Object] },
     warnings: [] } }
C:\Users\mika\AppData\Roaming\npm\node_modules\drakov\node_modules\drafter.js\lib\drafter.nomem.js:1
(function (exports, require, module, __filename, __dirname) { ((function(f){if(typeof exports==="object"&&typeof module!
=="undefined"){module.exports=f()}else if(typeof define==="function"&&define.amd){define([],f)}else{var g;if(typeof wind
ow!=="undefined"){g=window}else if(typeof global!=="undefined"){g=global}else if(typeof self!=="undefined"){g=self}else{
g=this}g.drafter=f()}}))((function(){var module;var Module={"ready":false,"log":(function(text){console.log("drafter.js:
 "+text)}),"logErr":(function(text){console.error("drafter.js: "+text)}),"onRuntimeInitialized":(function(){this.ready=t
rue})};var Module;if(!Module)Module=(typeof Module!=="undefined"?Module:null)||{};var moduleOverrides={};for(var key in
Module){if(Module.hasOwnProperty(key)){moduleOverrides[key]=Module[key]}}var ENVIRONMENT_IS_WEB=false;var ENVIRONMENT_IS
_WORKER=false;var ENVIRONMENT_IS_NODE=false;var ENVIRONMENT_IS_SHELL=false;if(Mod

Error: Error parsing blueprint!
    at Object.Module.parse (C:\Users\mika\AppData\Roaming\npm\node_modules\drakov\node_modules\drafter.js\lib\drafter.no
mem.js:20:7869)
    at C:\Users\mika\AppData\Roaming\npm\node_modules\drakov\lib\parse\blueprint.js:13:17
    at C:\Users\mika\AppData\Roaming\npm\node_modules\drakov\node_modules\async\lib\async.js:718:13
    at iterate (C:\Users\mika\AppData\Roaming\npm\node_modules\drakov\node_modules\async\lib\async.js:262:13)
    at async.forEachOfSeries.async.eachOfSeries (C:\Users\mika\AppData\Roaming\npm\node_modules\drakov\node_modules\asyn
c\lib\async.js:281:9)
    at _parallel (C:\Users\mika\AppData\Roaming\npm\node_modules\drakov\node_modules\async\lib\async.js:717:9)
    at Object.async.series (C:\Users\mika\AppData\Roaming\npm\node_modules\drakov\node_modules\async\lib\async.js:739:9)
    at C:\Users\mika\AppData\Roaming\npm\node_modules\drakov\lib\middleware\route-map.js:23:15
    at f (C:\Users\mika\AppData\Roaming\npm\node_modules\drakov\node_modules\once\once.js:25:25)
    at Glob.<anonymous> (C:\Users\mika\AppData\Roaming\npm\node_modules\drakov\node_modules\glob\glob.js:151:7)

**Comment by cesarhdz** [comment]
+1

**Comment by starek4** [comment]
+1

**Comment by slodreamer** [comment]
+1

**Comment by niaomingjian** [comment]
+1

**Comment by niaomingjian** [comment]
I have to change the `carriage return(s)` to fix the problem( `CR+LF =>LF`). 
If no need to change the `carriage return(s)`, It would be great.

**Comment by zqhong** [comment]
@niaomingjian good job, it works. thank you.
