### ISSUE TITLE
Error on ignoreHeader command line argument

### ISSUE THREAD

**Issue by kamihouse** [Aconex/drakov#180]
When using the commands `--ignoreHeader Cookie` and `--ignoreHeader Authorization` I get the following error when accessing a resource:

`"drakov": "^1.0.4",`

```
TypeError: ignoreHeaders.map is not a function
    at Object.exports.matchesHeader (/node_modules/drakov/lib/content.js:114:53)
    at /node_modules/drakov/lib/handler-filter.js:6:24
    at Array.filter (<anonymous>)
    at Object.exports.filterHandlers (/node_modules/drakov/lib/handler-filter.js:36:37)
    at /node_modules/drakov/lib/middleware/route-handlers.js:26:38
    at Array.forEach (<anonymous>)
    at middleware (/node_modules/drakov/lib/middleware/route-handlers.js:15:35)
    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/node_modules/express/lib/router/index.js:317:13)
    at /node_modules/express/lib/router/index.js:284:7
```

![captura de tela 2018-06-04 as 10 56 46](https://user-images.githubusercontent.com/892340/40921542-1176de7a-67e6-11e8-9476-040f86596b74.png)

**Comment by subinvarghesein** [comment]
@aj-jaswanth could this be related to your commit: https://github.com/Aconex/drakov/commit/5e6c9787c4dac5608a86295364c89a3479ff8cc1

**Comment by aj-jaswanth** [comment]
Hi @kamihouse, are you seeing this issue when using both the `--ignoreHeader Cookie --ignoreHeader Authorization` together?

I saw this issue happening when only one `--ignoreHeader` is specified.
This issue was fixed as part of https://github.com/Aconex/drakov/commit/5e6c9787c4dac5608a86295364c89a3479ff8cc1 which is not yet released.

**Comment by kamihouse** [comment]
Hi @aj-jaswanth 
Yes, the problem happens when I specify only one `--ignoreHeader`.

Thank you for your help!
